name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run code formatting check
      run: uv run black --check backend/ main.py
    
    - name: Run import sorting check
      run: uv run isort --check-only backend/ main.py
    
    - name: Run linting
      run: uv run flake8 backend/ main.py
    
    - name: Run type checking
      run: uv run mypy backend/ main.py
    
    - name: Run tests
      run: cd backend && uv run pytest
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}